-- 1. DROP TABLES (Order matters to handle foreign keys)
DROP TABLE IF EXISTS notifications CASCADE;
DROP TABLE IF EXISTS appointments CASCADE;
DROP TABLE IF EXISTS time_slots CASCADE;
DROP TABLE IF EXISTS users CASCADE;

-- 2. CREATE USERS TABLE
CREATE TABLE users (
    id BIGSERIAL PRIMARY KEY,
    email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    name VARCHAR(255) NOT NULL,
    role VARCHAR(50) NOT NULL CHECK (role IN ('ROLE_CUSTOMER', 'ROLE_PROVIDER', 'ROLE_ADMIN')),
    is_active BOOLEAN NOT NULL DEFAULT TRUE
);

-- 3. CREATE TIME_SLOTS TABLE
CREATE TABLE time_slots (
    id BIGSERIAL PRIMARY KEY,
    provider_id BIGINT NOT NULL,
    start_time TIMESTAMP NOT NULL,
    end_time TIMESTAMP NOT NULL,
    is_booked BOOLEAN NOT NULL DEFAULT FALSE,
    is_cancelled BOOLEAN DEFAULT FALSE,
    version BIGINT,
    CONSTRAINT fk_provider FOREIGN KEY (provider_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT uq_provider_start_time UNIQUE (provider_id, start_time)
);

-- 4. CREATE APPOINTMENTS TABLE
CREATE TABLE appointments (
    id BIGSERIAL PRIMARY KEY,
    customer_id BIGINT NOT NULL,
    slot_id BIGINT NOT NULL,
    status VARCHAR(50) NOT NULL CHECK (status IN ('PENDING', 'BOOKED', 'CANCELLED', 'COMPLETED')),
    booked_at TIMESTAMP NOT NULL DEFAULT NOW(),
    cancelled_at TIMESTAMP,
    CONSTRAINT fk_customer FOREIGN KEY (customer_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT fk_slot FOREIGN KEY (slot_id) REFERENCES time_slots (id) ON DELETE CASCADE
);

-- 5. CREATE NOTIFICATIONS TABLE
CREATE TABLE notifications (
    id BIGSERIAL PRIMARY KEY,
    recipient_id BIGINT NOT NULL,
    message VARCHAR(255) NOT NULL,
    is_read BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_recipient FOREIGN KEY (recipient_id) REFERENCES users (id) ON DELETE CASCADE
);